version: '2.3'

services:
  base:
    environment:
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - GH_ORG
      - GH_TOKEN
      - 'GIT_EMAIL=te+semantic-release@vitaler.co'
      - GITHUB_TOKEN
      - NPM_TOKEN
