env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY: "quay.io/vital/build-cache"

steps:
  - name: ":docker: :quay: Build and push container to Quay"
    key: create-image
    agents:
      queue: docker-build
    plugins:
      - docker-compose#v3.3.0:
          build: base
          image-name: "vitalizer-${BUILDKITE_COMMIT}-${BUILDKITE_BUILD_NUMBER}"

  - name: ":eslint: Lint"
    key: linting
    depends_on: create-image
    command: yarn lint
    plugins:
      - docker-compose#v3.3.0:
          run: base

  - name: ":yarn: Run Tests"
    key: tests
    depends_on: create-image
    command: test/task/e2e-simple.sh
    plugins:
      - docker-compose#v3.3.0:
          run: base

  - name: ":npm: :github: Release package to Github Registry"
    depends_on:
      - "linting"
      - "tests"
    branches: master next next-major beta alpha
    command: semantic-release
    timeout_in_minutes: 2
    plugins:
      - docker-compose#v3.3.0:
          run: base
