env:
  COMMIT_TAG: vitalizer-${BUILDKITE_COMMIT}

steps:
  - name: ":docker: :quay: Build and push container to Quay"
    key: create-image
    agents:
      queue: docker-build
    plugins:
      vital-software/docker-compose#vital-v1.8:
        build: base
        image_repository: quay.io/vital/build-cache
        image-name: ${COMMIT_TAG}

  - name: ":eslint: Lint"
    key: linting
    depends_on: create-image
    command: yarn lint
    plugins:
      vital-software/docker-compose#vital-v1.8:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        run: base

  - name: ":yarn: Run Tests"
    key: tests
    depends_on: create-image
    command: test/task/e2e-simple.sh
    plugins:
      vital-software/docker-compose#vital-v1.8:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        run: base

  - name: ":npm: :github: Release package to Github Registry"
    depends_on:
      - "linting"
      - "tests"
    branches: master next next-major beta alpha
    command: semantic-release
    timeout_in_minutes: 2
    plugins:
      vital-software/docker-compose#vital-v1.8:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        run: base
